platform :ios, '15.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', 'Debug' => :debug, 'Profile' => :release, 'Release' => :release

# If you encounter issues running pod install, run `flutter pub get` first.
# This Podfile is compatible with Flutter. Keep it next to Runner.xcodeproj.

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise 'Flutter Generated.xcconfig not found. Run `flutter pub get` and try again.'
  end
  File.read(generated_xcode_build_settings_path).match(/FLUTTER_ROOT=([^\n]+)/)[1]
end

require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper'), __FILE__)

flutter_ios_podfile_setup

target 'Runner' do
  # Add any plugin-specific pod configuration here.
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
